steps:
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: 'b013c61c-a558-40f3-847c-81cd6de4bee7'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'CFX-DEV-Demo'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateAzureStorage/azuredeploy.json'
    deploymentMode: 'Incremental'
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: 'CfxDemoResourceGroup'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'CFX-DEV-Demo'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    deploymentMode: 'Incremental'